"""Phone number

Revision ID: 77c26a9d602b
Revises: e82499335a51
Create Date: 2023-08-31 16:52:41.027632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c26a9d602b'
down_revision: Union[str, None] = 'e82499335a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone_numbre', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'phone_numbre')
    # ### end Alembic commands ###
