"""Added name column to post table

Revision ID: a9e2fbc770e7
Revises: 76e8240d0031
Create Date: 2023-10-21 17:41:01.654313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e2fbc770e7'
down_revision: Union[str, None] = '76e8240d0031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'user_name')
    # ### end Alembic commands ###
